# Generated by Django 2.1.7 on 2019-07-03 08:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, null='True')),
                ('faculty', models.CharField(default='', max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='exam_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, null='True')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('no_of_questions', models.IntegerField()),
                ('attempts_allowed', models.IntegerField()),
                ('pass_percentage', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.course')),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MatchTheColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null='True')),
                ('answer', models.TextField(blank=True, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_no', models.IntegerField()),
                ('option_value', models.TextField(blank=True, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='question_bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null='True')),
                ('description', models.TextField(blank=True, null='True')),
                ('score', models.FloatField()),
                ('status', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.exam_detail')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.level')),
            ],
        ),
        migrations.CreateModel(
            name='question_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.IntegerField()),
                ('registered', models.IntegerField(default=0)),
                ('view_answers', models.IntegerField(default=0)),
                ('answered', models.IntegerField(default=0)),
                ('registered_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.exam_detail')),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null='True')),
                ('score', models.FloatField()),
                ('verify', models.IntegerField(default=0)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.question_bank')),
                ('registration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.registration')),
            ],
        ),
        migrations.CreateModel(
            name='subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, null='True')),
                ('status', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, null='True')),
                ('status', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('account_type', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.topic'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.user'),
        ),
        migrations.AddField(
            model_name='question_bank',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.question_type'),
        ),
        migrations.AddField(
            model_name='question_bank',
            name='subtopic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.subtopic'),
        ),
        migrations.AddField(
            model_name='option',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.question_bank'),
        ),
        migrations.AddField(
            model_name='matchthecolumns',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.question_bank'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.question_bank'),
        ),
    ]
